# Generated by Django 2.2.5 on 2019-10-20 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('barcode_no', models.TextField(auto_created=True, unique=True)),
                ('barcode_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('user_product_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('exp_date', models.DateField()),
                ('barcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_waste_management_app.Barcode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
