# Generated by Django 2.2.6 on 2019-10-19 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('barcode_no', models.IntegerField(auto_created=True, unique=True)),
                ('barcode_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('username', models.TextField(unique=True)),
                ('salt', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('barcode_no', models.IntegerField()),
                ('exp_date', models.DateField()),
                ('product_name', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_waste_management_app.User')),
            ],
        ),
    ]
