# Generated by Django 2.2.5 on 2019-10-19 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_waste_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproduct',
            name='barcode_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food_waste_management_app.Barcode'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='food_waste_management_app.User')),
            ],
        ),
    ]
